#!/usr/bin/env bash

##############################################################################
##
##  Changelog creation script for use with Git Shell & Drone.io
##  Created by Funwayguy for NPCIntegration
##
##############################################################################

# Offline Debug Variables
#DRONE_BUILD_NUMBER=0
#ver_num="BQ_NPC_VER"

# Create document for update notice
echo $ver_num > version.txt
echo "https://drone.io/github.com/Funwayguy/NPCIntegration/files" >> version.txt
git log -1 --pretty=format:"%B" >> version.txt